<?php

/**
 * Created by PhpStorm.
 * User: atellez
 * Date: 18/11/16
 * Time: 8:47
 */
require_once "Controller.php";

class LibroController extends Controller
{
    public function manageGetVerb(Request $request)
    {
        parent::manageGetVerb($request); // TODO: Change the autogenerated stub
    }
}